### PR TITLE
Our sponsers

### PR DESCRIPTION
**Pull request by DevanshuTripathi**
Capture

### CODE REVIEW

**Comment by DevanshuTripathi** [comment]
Couldnt get the exact background from the assets so settled for another background. Can change the background.

**Review by Harshilmalhotra — CHANGES_REQUESTED** [review]
minor changes needed to be done in your code.

1. Background needs to be bit dark.
2. Our sponsors is not visible. try changing font color.

your code: 
image


figma:

image

**Comment by DevanshuTripathi** [comment]
image
image
Changed background and added mobile responsiveness

**Review by Harshilmalhotra — APPROVED** [review]
Good work.
I am merging this PR, but still 2 horizontal lines are missing.

**Comment by DevanshuTripathi** [comment]
the horizontal grid lines maybe my disapearing because of screen width issues. On my system it shows. But on maybe a smaller laptop it may vanish because of no space.

**Pull request merged**
